# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'firestore' do

    # Pods for saturn_five_react_app
    pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge',
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket',
      'RCTImage',
      'RCTNetwork',
      'DevSupport'
        # 'Core',
    ]
  
    # Pods for reactnativefirebase
    pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios/'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firestore

  target 'firestore-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'firestoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
